"""Independent generator for the GS-103 golden fixtures (design-v0.2 §7.3/§7.4).

It lays out every field with struct and computes CRC-16/CCITT-FALSE bitwise; it does not use the Java encoder, so a
golden-fixture test that passes is an independent check of the layout. Never regenerate fixtures with the Java code.

Usage (from the repository root; Python 3, standard library only):
    python tools/gen_fixtures.py src/test/resources/fixtures/v1
The output must be byte-identical to the committed files: `git diff --exit-code src/test/resources/fixtures/v1`.
"""
import struct, os, sys

out_dir = sys.argv[1]

def crc16_ccitt_false(data):
    crc = 0xFFFF
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) if crc & 0x8000 else (crc << 1)
            crc &= 0xFFFF
    return crc

assert crc16_ccitt_false(b"123456789") == 0x29B1

def emit(name, header, fields):
    lines = ["# " + h for h in header]
    total = b""
    for label, raw in fields:
        lines.append(" ".join("%02x" % b for b in raw).ljust(72) + "# " + label)
        total += raw
    with open(os.path.join(out_dir, name), "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return total

# Minute slot, slotLayout 1
epoch_minute = 29_318_460          # 2025-09-29T..Z-ish; any non-zero minute
state_samples = [0, 0, 0, 0, 2, 50, 0, 3, 0, 3]   # power_starved 2, running 50, output_blocked 3, idle 3
fields = [
    ("off 0  i32 epochMinute = %d" % epoch_minute, struct.pack(">i", epoch_minute)),
    ("off 4  u8  samples = 58", struct.pack(">B", 58)),
    ("off 5  u8  expectedSamples = 60", struct.pack(">B", 60)),
    ("off 6  u8  gapMask = chunk_unloaded|target_missing (0x05)", struct.pack(">B", 0x05)),
    ("off 7  u8  lastStateCode = 5 (running)", struct.pack(">B", 5)),
    ("off 8  u8x10 stateSamples", bytes(state_samples)),
    ("off 18 u8  maintenanceMax = 1", struct.pack(">B", 1)),
    ("off 19 u8  flags = recipesCounterReset|serverStartMinute (0x05)", struct.pack(">B", 0x05)),
    ("off 20 u16 serverTicks = 1180", struct.pack(">H", 1180)),
    ("off 22 u8  euSamples = 50", struct.pack(">B", 50)),
    ("off 23 u8  reserved = 0", struct.pack(">B", 0)),
    ("off 24 i64 euPerTickAvg = 1850", struct.pack(">q", 1850)),
    ("off 32 i64 euPerTickMin = -64", struct.pack(">q", -64)),
    ("off 40 i64 euPerTickMax = 2133", struct.pack(">q", 2133)),
    ("off 48 i64 energyStoredLast = 1600000", struct.pack(">q", 1_600_000)),
    ("off 56 i32 recipesCompletedDelta = 12", struct.pack(">i", 12)),
    ("off 60 u16 reserved = 0", struct.pack(">H", 0)),
]
body = b"".join(raw for _, raw in fields)
assert len(body) == 62
crc = crc16_ccitt_false(body)
fields.append(("off 62 u16 CRC-16/CCITT-FALSE over 0..61 = 0x%04x" % crc, struct.pack(">H", crc)))
slot = emit("minute_slot_valid.hex",
            ["design-v0.2 §7.4 minute slot (slotLayout 1), 64 B big-endian. Generated independently of the Java",
             "encoder by tools/gen_fixtures.py (bitwise CRC-16/CCITT-FALSE, check value 0x29B1 asserted)."], fields)
assert len(slot) == 64

# Torn slot: byte 33 (inside euPerTickMin) changed after the CRC was written.
torn_fields = list(fields)
label, raw = torn_fields[12]
torn_raw = bytearray(raw); torn_raw[1] ^= 0x40
torn_fields[12] = (label + " -- byte 33 flipped (0x40), CRC not updated: torn", bytes(torn_raw))
emit("minute_slot_torn.hex",
     ["minute_slot_valid.hex with byte 33 flipped and the old CRC kept: a torn write, which must read as a gap.",
      "Generated by tools/gen_fixtures.py."],
     torn_fields)

# Minute slot with a far-away (stale) epoch, CRC valid.
stale_fields = list(fields[:-1])
stale_fields[0] = ("off 0  i32 epochMinute = %d (1440 minutes before the valid slot)" % (epoch_minute - 1440),
                   struct.pack(">i", epoch_minute - 1440))
stale_body = b"".join(raw for _, raw in stale_fields)
stale_crc = crc16_ccitt_false(stale_body)
stale_fields.append(("off 62 u16 CRC = 0x%04x" % stale_crc, struct.pack(">H", stale_crc)))
emit("minute_slot_stale.hex",
     ["minute_slot_valid.hex one day earlier, CRC valid. Same ring index as the valid slot, but outside the",
      "window newest-1439..newest once the valid slot is newest: stale, reads as a gap. Generated by tools/gen_fixtures.py."], stale_fields)

# Second sample, 28 B
flags = 0x01 | 0x02 | 0x04 | 0x08 | 0x20 | 0x40 | 0x80   # active, allowedToWork, formedKnown, formed, hasEu, hasEnergy, valid
sfields = [
    ("off 0  i32 epochSec = 1759107600", struct.pack(">i", 1_759_107_600)),
    ("off 4  u8  stateCode = 5 (running)", struct.pack(">B", 5)),
    ("off 5  u8  gapReason = 0 (none)", struct.pack(">B", 0)),
    ("off 6  u8  flags = 0x%02x (active, allowedToWork, formedKnown, formed, hasEu, hasEnergy, valid)" % flags,
     struct.pack(">B", flags)),
    ("off 7  u8  maintenanceIssues = 2", struct.pack(">B", 2)),
    ("off 8  u16 progress x10000 = 4200", struct.pack(">H", 4200)),
    ("off 10 u16 reserved = 0", struct.pack(">H", 0)),
    ("off 12 i64 euPerTick = -1920 (generation)", struct.pack(">q", -1920)),
    ("off 20 i64 energyStored = 1200000", struct.pack(">q", 1_200_000)),
]
s = emit("second_sample.hex", ["design-v0.2 §7.3 second sample, 28 B big-endian. Generated independently of the Java encoder by",
                                    "tools/gen_fixtures.py."], sfields)
assert len(s) == 28

gfields = [
    ("off 0  i32 epochSec = 1759107601", struct.pack(">i", 1_759_107_601)),
    ("off 4  u8  stateCode = 0 (gap)", struct.pack(">B", 0)),
    ("off 5  u8  gapReason = 3 (target_missing: bit 2 + 1)", struct.pack(">B", 3)),
    ("off 6  u8  flags = 0 (not valid)", struct.pack(">B", 0)),
    ("off 7  u8  maintenanceIssues = 0", struct.pack(">B", 0)),
    ("off 8  u16 progress = 0", struct.pack(">H", 0)),
    ("off 10 u16 reserved = 0", struct.pack(">H", 0)),
    ("off 12 i64 euPerTick = 0", struct.pack(">q", 0)),
    ("off 20 i64 energyStored = 0", struct.pack(">q", 0)),
]
g = emit("second_gap.hex", ["design-v0.2 §7.3 gap second (target_missing), 28 B big-endian. Generated by tools/gen_fixtures.py."], gfields)
assert len(g) == 28
print("ok crc=0x%04x stale_crc=0x%04x" % (crc, stale_crc))
