"""Independent generator for the GS-103 golden fixtures (design-v0.2 §7.3/§7.4).

It lays out every field with struct and computes CRC-16/CCITT-FALSE bitwise; it does not use the Java encoder, so a
golden-fixture test that passes is an independent check of the layout. Never regenerate fixtures with the Java code.

Usage (from the repository root; Python 3, standard library only):
    python tools/gen_fixtures.py src/test/resources/fixtures/v1
The output must be byte-identical to the committed files: `git diff --exit-code src/test/resources/fixtures/v1`.
"""
import gzip, struct, os, sys

out_dir = sys.argv[1]

def crc16_ccitt_false(data):
    crc = 0xFFFF
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) if crc & 0x8000 else (crc << 1)
            crc &= 0xFFFF
    return crc

assert crc16_ccitt_false(b"123456789") == 0x29B1

def emit(name, header, fields):
    lines = ["# " + h for h in header]
    total = b""
    for label, raw in fields:
        lines.append(" ".join("%02x" % b for b in raw).ljust(72) + "# " + label)
        total += raw
    with open(os.path.join(out_dir, name), "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return total

# Minute slot, slotLayout 1
epoch_minute = 29_318_460          # 2025-09-29T..Z-ish; any non-zero minute
state_samples = [0, 0, 0, 0, 2, 50, 0, 3, 0, 3]   # power_starved 2, running 50, output_blocked 3, idle 3
fields = [
    ("off 0  i32 epochMinute = %d" % epoch_minute, struct.pack(">i", epoch_minute)),
    ("off 4  u8  samples = 58", struct.pack(">B", 58)),
    ("off 5  u8  expectedSamples = 60", struct.pack(">B", 60)),
    ("off 6  u8  gapMask = chunk_unloaded|target_missing (0x05)", struct.pack(">B", 0x05)),
    ("off 7  u8  lastStateCode = 5 (running)", struct.pack(">B", 5)),
    ("off 8  u8x10 stateSamples", bytes(state_samples)),
    ("off 18 u8  maintenanceMax = 1", struct.pack(">B", 1)),
    ("off 19 u8  flags = recipesCounterReset|serverStartMinute (0x05)", struct.pack(">B", 0x05)),
    ("off 20 u16 serverTicks = 1180", struct.pack(">H", 1180)),
    ("off 22 u8  euSamples = 50", struct.pack(">B", 50)),
    ("off 23 u8  reserved = 0", struct.pack(">B", 0)),
    ("off 24 i64 euPerTickAvg = 1850", struct.pack(">q", 1850)),
    ("off 32 i64 euPerTickMin = -64", struct.pack(">q", -64)),
    ("off 40 i64 euPerTickMax = 2133", struct.pack(">q", 2133)),
    ("off 48 i64 energyStoredLast = 1600000", struct.pack(">q", 1_600_000)),
    ("off 56 i32 recipesCompletedDelta = 12", struct.pack(">i", 12)),
    ("off 60 u16 reserved = 0", struct.pack(">H", 0)),
]
body = b"".join(raw for _, raw in fields)
assert len(body) == 62
crc = crc16_ccitt_false(body)
fields.append(("off 62 u16 CRC-16/CCITT-FALSE over 0..61 = 0x%04x" % crc, struct.pack(">H", crc)))
slot = emit("minute_slot_valid.hex",
            ["design-v0.2 §7.4 minute slot (slotLayout 1), 64 B big-endian. Generated independently of the Java",
             "encoder by tools/gen_fixtures.py (bitwise CRC-16/CCITT-FALSE, check value 0x29B1 asserted)."], fields)
assert len(slot) == 64

# Torn slot: byte 33 (inside euPerTickMin) changed after the CRC was written.
torn_fields = list(fields)
label, raw = torn_fields[12]
torn_raw = bytearray(raw); torn_raw[1] ^= 0x40
torn_fields[12] = (label + " -- byte 33 flipped (0x40), CRC not updated: torn", bytes(torn_raw))
emit("minute_slot_torn.hex",
     ["minute_slot_valid.hex with byte 33 flipped and the old CRC kept: a torn write, which must read as a gap.",
      "Generated by tools/gen_fixtures.py."],
     torn_fields)

# Minute slot with a far-away (stale) epoch, CRC valid.
stale_fields = list(fields[:-1])
stale_fields[0] = ("off 0  i32 epochMinute = %d (1440 minutes before the valid slot)" % (epoch_minute - 1440),
                   struct.pack(">i", epoch_minute - 1440))
stale_body = b"".join(raw for _, raw in stale_fields)
stale_crc = crc16_ccitt_false(stale_body)
stale_fields.append(("off 62 u16 CRC = 0x%04x" % stale_crc, struct.pack(">H", stale_crc)))
emit("minute_slot_stale.hex",
     ["minute_slot_valid.hex one day earlier, CRC valid. Same ring index as the valid slot, but outside the",
      "window newest-1439..newest once the valid slot is newest: stale, reads as a gap. Generated by tools/gen_fixtures.py."], stale_fields)

# Second sample, 28 B
flags = 0x01 | 0x02 | 0x04 | 0x08 | 0x20 | 0x40 | 0x80   # active, allowedToWork, formedKnown, formed, hasEu, hasEnergy, valid
sfields = [
    ("off 0  i32 epochSec = 1759107600", struct.pack(">i", 1_759_107_600)),
    ("off 4  u8  stateCode = 5 (running)", struct.pack(">B", 5)),
    ("off 5  u8  gapReason = 0 (none)", struct.pack(">B", 0)),
    ("off 6  u8  flags = 0x%02x (active, allowedToWork, formedKnown, formed, hasEu, hasEnergy, valid)" % flags,
     struct.pack(">B", flags)),
    ("off 7  u8  maintenanceIssues = 2", struct.pack(">B", 2)),
    ("off 8  u16 progress x10000 = 4200", struct.pack(">H", 4200)),
    ("off 10 u16 reserved = 0", struct.pack(">H", 0)),
    ("off 12 i64 euPerTick = -1920 (generation)", struct.pack(">q", -1920)),
    ("off 20 i64 energyStored = 1200000", struct.pack(">q", 1_200_000)),
]
s = emit("second_sample.hex", ["design-v0.2 §7.3 second sample, 28 B big-endian. Generated independently of the Java encoder by",
                                    "tools/gen_fixtures.py."], sfields)
assert len(s) == 28

gfields = [
    ("off 0  i32 epochSec = 1759107601", struct.pack(">i", 1_759_107_601)),
    ("off 4  u8  stateCode = 0 (gap)", struct.pack(">B", 0)),
    ("off 5  u8  gapReason = 3 (target_missing: bit 2 + 1)", struct.pack(">B", 3)),
    ("off 6  u8  flags = 0 (not valid)", struct.pack(">B", 0)),
    ("off 7  u8  maintenanceIssues = 0", struct.pack(">B", 0)),
    ("off 8  u16 progress = 0", struct.pack(">H", 0)),
    ("off 10 u16 reserved = 0", struct.pack(">H", 0)),
    ("off 12 i64 euPerTick = 0", struct.pack(">q", 0)),
    ("off 20 i64 energyStored = 0", struct.pack(">q", 0)),
]
g = emit("second_gap.hex", ["design-v0.2 §7.3 gap second (target_missing), 28 B big-endian. Generated by tools/gen_fixtures.py."], gfields)
assert len(g) == 28
print("ok crc=0x%04x stale_crc=0x%04x" % (crc, stale_crc))

# ---------------------------------------------------------------------------
# GS-109 fixtures: the .gsh file header (design-v0.2 section 8.2) and registry.dat (section 8.3).
# ---------------------------------------------------------------------------

def crc32_ieee(data):
    """CRC-32 (IEEE 802.3), computed bitwise so it shares no code with zlib."""
    crc = 0xFFFFFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ 0xEDB88320 if crc & 1 else crc >> 1
    return crc ^ 0xFFFFFFFF

assert crc32_ieee(b"123456789") == 0xCBF43926

# A pinned sensor UUID; any value works, the test uses the same one.
GSH_UUID_MSB = 0x3FA2C1D0A1B24C3D
GSH_UUID_LSB = -0x5E6F708192A3B4C5      # a negative low half, so sign handling is covered
GSH_CREATED = 1_759_000_000

def gsh_header(format_version, sensor_kind, slot_layout, msb, lsb, created, break_crc=False):
    fields = [
        ("off 0  4 B magic GSH1", b"GSH1"),
        ("off 4  u16 formatVersion = %d" % format_version, struct.pack(">H", format_version)),
        ("off 6  u16 slotSize = 64", struct.pack(">H", 64)),
        ("off 8  u16 slotCount = 1440", struct.pack(">H", 1440)),
        ("off 10 u8  sensorKind = %d" % sensor_kind, struct.pack(">B", sensor_kind)),
        ("off 11 u8  slotLayout = %d" % slot_layout, struct.pack(">B", slot_layout)),
        ("off 12 i64 uuid msb", struct.pack(">q", msb)),
        ("off 20 i64 uuid lsb", struct.pack(">q", lsb)),
        ("off 28 i64 createdEpochSec = %d" % created, struct.pack(">q", created)),
        ("off 36 24 B reserved = 0", bytes(24)),
    ]
    body = b"".join(raw for _, raw in fields)
    assert len(body) == 60
    crc = crc32_ieee(body)
    if break_crc:
        crc ^= 0x00000001
    fields.append(("off 60 u32 CRC-32 of bytes 0..59 = 0x%08x%s"
                   % (crc, " (deliberately wrong)" if break_crc else ""),
                   struct.pack(">I", crc)))
    return fields

gsh = emit("gsh_header_valid.hex",
           ["design-v0.2 section 8.2 history file header (format 1, sensorKind 0, slotLayout 1), 64 B big-endian.",
            "The whole file is 64 + 1440*64 = 92,224 B; only the header is pinned here. Generated independently of",
            "the Java encoder by tools/gen_fixtures.py (bitwise CRC-32, check value 0xCBF43926 asserted)."],
           gsh_header(1, 0, 1, GSH_UUID_MSB, GSH_UUID_LSB, GSH_CREATED))
assert len(gsh) == 64

emit("gsh_header_bad_crc.hex",
     ["gsh_header_valid.hex with the header CRC-32 flipped in its lowest bit: the file must read as corrupt and be",
      "renamed to .corrupt-<epochMs>, never deleted or overwritten. Generated by tools/gen_fixtures.py."],
     gsh_header(1, 0, 1, GSH_UUID_MSB, GSH_UUID_LSB, GSH_CREATED, break_crc=True))

emit("gsh_header_v2.hex",
     ["A format-2 header with a valid CRC: a v0.2 build cannot read it and must rename it to .unsupported-v2.",
      "Generated by tools/gen_fixtures.py."],
     gsh_header(2, 0, 1, GSH_UUID_MSB, GSH_UUID_LSB, GSH_CREATED))

emit("gsh_header_flow_layout.hex",
     ["sensorKind 1 (v0.3 item flow) with slotLayout 2, CRC valid: a reserved layout this build cannot read, so the",
      "file is renamed to .unsupported-v1 rather than reinterpreted (section 8.2). Generated by",
      "tools/gen_fixtures.py."],
     gsh_header(1, 1, 2, GSH_UUID_MSB, GSH_UUID_LSB, GSH_CREATED))

# --- registry.dat (section 8.3): gzipped NBT, written here without any NBT library ---

TAG_END, TAG_BYTE, TAG_INT, TAG_LONG, TAG_STRING, TAG_LIST, TAG_COMPOUND = 0, 1, 3, 4, 8, 9, 10

def nbt_name(text):
    raw = text.encode("utf-8")
    return struct.pack(">H", len(raw)) + raw

def nbt_tag(tag_id, name, payload):
    return bytes([tag_id]) + nbt_name(name) + payload

def nbt_byte(name, value):
    return nbt_tag(TAG_BYTE, name, struct.pack(">b", value))

def nbt_int(name, value):
    return nbt_tag(TAG_INT, name, struct.pack(">i", value))

def nbt_long(name, value):
    return nbt_tag(TAG_LONG, name, struct.pack(">q", value))

def nbt_string(name, value):
    return nbt_tag(TAG_STRING, name, nbt_name(value))

def nbt_compound_payload(entries):
    return b"".join(entries) + bytes([TAG_END])

def nbt_compound(name, entries):
    return nbt_tag(TAG_COMPOUND, name, nbt_compound_payload(entries))

def nbt_compound_list(name, elements):
    payload = bytes([TAG_COMPOUND]) + struct.pack(">i", len(elements))
    return nbt_tag(TAG_LIST, name, payload + b"".join(nbt_compound_payload(e) for e in elements))

# Two runs: one clean, one still open (an unclean stop). On load the open one is closed at `saved`.
REG_SAVED = 1_759_107_600
REG_RUNS = [
    [nbt_long("start", 1_759_100_000), nbt_long("stop", 1_759_103_000)],
    [nbt_long("start", 1_759_105_000), nbt_long("stop", 0)],
]

def reg_entry(msb, lsb, kind, dim, x, y, z, side, owner, label, meta_id, meta, machine, status, state, cause,
              created, seen, since, extra=None):
    fields = [nbt_long("idM", msb), nbt_long("idL", lsb), nbt_byte("kind", kind), nbt_int("dim", dim),
              nbt_int("x", x), nbt_int("y", y), nbt_int("z", z), nbt_byte("side", side)]
    if owner is not None:
        fields += [nbt_long("owM", owner[0]), nbt_long("owL", owner[1]), nbt_string("owN", owner[2])]
    fields += [nbt_string("lbl", label), nbt_int("mi", meta_id), nbt_string("mn", meta),
               nbt_string("nm", machine), nbt_string("st", status), nbt_byte("state", state),
               nbt_byte("cause", cause), nbt_long("ct", created), nbt_long("seen", seen), nbt_long("since", since)]
    if extra:
        fields += extra
    return fields

registry_root = nbt_compound("", [
    nbt_int("v", 1),
    nbt_long("saved", REG_SAVED),
    nbt_compound_list("runs", REG_RUNS),
    nbt_compound_list("entries", [
        # A machine sensor, owned, with one key a v0.2 build does not define (kept verbatim on save).
        reg_entry(0x3FA2C1D0A1B24C3D, -0x5E6F708192A3B4C5, 0, 0, 120, 64, -30, 5,
                  (0x1122334455667788, 0x0A0B0C0D0E0F1011, "Steve"), "EBF North", 1001,
                  "Electric Blast Furnace", "Electric Blast Furnace", "running", 0, 0,
                  1_758_900_000, 1_759_107_000, 1_759_106_000,
                  extra=[nbt_int("xtra", 7)]),
        # A tombstone: detached, unowned, no label.
        reg_entry(0x0000000000000042, 0x0000000000000043, 0, -1, 8, 70, 9, 2, None, "", 0, "", "", "",
                  3, 1, 1_758_800_000, 1_759_000_000, 1_759_000_500),
        # design-v0.3 kind 1 (item flow): a v0.2 build must keep this entry byte for byte and never sample it.
        reg_entry(0x00000000DEADBEEF, 0x00000000CAFEBABE, 1, 0, 5, 64, 5, 3, None, "Pump", 0, "", "", "",
                  0, 0, 1_758_700_000, 1_759_100_000, 1_759_100_000,
                  extra=[nbt_byte("tier", 4), nbt_byte("lastIo", 1)]),
    ]),
    # A root key from a future version, kept verbatim as well.
    nbt_string("future", "v0.3"),
])

registry_gz = gzip.compress(registry_root, mtime=0)

def emit_blob(name, header, blob):
    lines = ["# " + h for h in header]
    for off in range(0, len(blob), 16):
        lines.append(" ".join("%02x" % b for b in blob[off:off + 16]))
    with open(os.path.join(out_dir, name), "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return blob

emit_blob("registry_v1.nbt.gz.hex",
          ["design-v0.2 section 8.3 registry.dat format 1: gzipped NBT, written here without any NBT library, so a",
           "test that decodes it checks the key names and types independently of the Java codec. It holds two runs",
           "(the second unclean, stop 0), two machine entries (one with an unknown key) and one design-v0.3 kind-1",
           "entry a v0.2 build must keep verbatim, plus an unknown root key. gzip mtime is 0, so re-runs are",
           "byte-identical. Generated by tools/gen_fixtures.py."],
          registry_gz)

print("ok gsh_crc=0x%08x registry=%d B gz" % (crc32_ieee(gsh[:60]), len(registry_gz)))
